### ISSUE TITLE
✨Implement Event API on the Consumer Domain

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#112]
#### Describe your issue

The Event API, which was originally designed to be a part of the Consumer API, is currently missing.
We only have mocks in place for this on the Consumer API. See: https://github.com/process-engine/consumer_api_core/blob/develop/src/consumer_api_service.ts#L176

This means, we cannot use the Consumer API to query or trigger events for a Correlation and/or a ProcessInstance.

#### Possible solution

**EDIT:**
Upon further reflection, I think we can just publish the events whenever we call the the corresponding `triggerMessageEvent` or `triggerSignalEvent` function at the Consumer API.

These types of Events are always send globally, without any associaton to a specific Correlation or ProcessInstance. 
Claim Checks asf. can be done at the receiving end, if at all required.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by roblen45** [comment]
I think we need both. 

Signals should work like described in Szenario A

and

Messages should work like described in Szenario B.

So we should create two separated methods "triggerSignal" and "triggerMessage" for that.

**Comment by ElRaptorus** [comment]
Separating the events sounds like a good idea.

However, I don't quite understand why we would need things like IAM verification for triggering messages, but not for triggering signals? 
Surely, triggering (not receiving!) either event should be verified, if IAM is required at all?
