### ISSUE TITLE
🐛 Can't deploy a process with empty lanes

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#115]
#### Describe your issue

When trying to upload a process with an empty lane, the ProcessEngine responds with the following message: 

```
422  Unprocessable Entity - The XML for process "xyz" could not be parsed.
```

#### How can others reproduce the issue?

* Create a Process with an empty lane
* Try to deploy this Process to the ProcessEngine

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

## Example

<details>
<summary>
:warning: Before creating the issue, click here to expand and follow the guide.
</summary>
<br>
  
1. Be sure to fill out **every** topic presented in this template. 
If a section is not valid or useful for your issue, feel free to remove it.

2. Use the attached Checklist to make sure your issue contains all relevant information.

3. Attach a label to your issue that reflects what your issue is all about.
**When your issue concerns only a specific platform, be sure to attach the label for that platform!**

4. Please use a fitting emoji at the beginning of your issue title.

Example 1 - Report a bug:
```md
:bug: Something is not working properly
```

Example 2 - Report a performance issue:
```md
:zap: Something is slower than it should be
```

Example 3 - Report a package vulnerability or security issue:
```md
:lock: Package xy produces vulnerabilites
```

```md
:lock: User XY has access to something he shouldn't have
```

Example 4 - Report missing test coverage: 
```md
:white_check_mark: Add tests for...
```

You can of course phrase your titles however you like.
Just be sure they are short, to the point and convey the general idea of the issue you are experiencing.
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your Issue with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

**Comment by ElRaptorus** [comment]
@robpal94 
Could you please attach the process file you tried to deploy? 

We already have quite a few diagrams in place who have a great deal more than two lanes (the diagrams for the Sublane Tests, for example).

I'm pretty sure your problem occurs somewhere else.

**Comment by robpal94** [comment]
Sure, moment.

**Comment by robpal94** [comment]
This only seems to happen, if one lane is empty.

https://gist.github.com/robpal94/8f834f3c7237e4261b751653480b650e

**Comment by ElRaptorus** [comment]
@robpal94 
I can confirm this. This happens, when the Lane is empty (dunno why anybody would want that, though). 

This is an issue with the Lane Parser used in ProcessEngineCore:
https://github.com/process-engine/process_engine_core/blob/develop/src/model/parser/process_lane_set_parser.ts#L33

This needs a NullOrUndefined-Check for the `flowNodeReferences` variable.

Feel free to fix this, if you like. 😉 

I adjusted the bug description accordingly.
