### ISSUE TITLE
🔒🐛 Using Mixed ExclusiveGateway Types causes unpredictable behavior

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#132]
#### Describe your issue

There are 4 possible types of `ExclusiveGateways` that the parser can currently recognize
- Split: A gateway has more outgoing sequence flows than incoming
- Join: A gateway has more incoming sequence flows than outgoing
- Mixed: The number of outgoing and incoming sequence flows is identical
- Undefined: The type of the gateway is indetermined. This usually happens, if no incoming and/or no outgoing Sequence Flows have been assigned to the Gateway

Using Mixed `ExclusiveGateways` is not supported at all.

Undefined `ExclusiveGateways` are ignored and are thus prone to causing non-descriptive runtime errors, like `Cannot read ID of undefined`.

Right now we have only implemented the first two scenarios in a very basic way.

**Basic Split Gateway**

A Split-Gateway will always pick the first outgoing SequenceFlow that has a truthy condition. If additional SequenceFlows have truthy conditions, they are ignored. 

This UseCase should actually cause an Error, because how are we to know which one of the truthy paths the User intended the ProcessInstance to take?
Just taking the first SequenceFlow whose condition matched could be dangerous (what if taking that path is not intended and leads to a task named `Launch nuclear missile`?)

**Basic Join Gateway**

This type of Gateway always assumes that only one outgoing SequenceFlow is present and is executed as such.

If there really is only one outgoing SequenceFlow, this is no problem. 

But if we have, say, 3 incoming and 2 outgoing SequenceFlows, the Gateway will assume that it is a "Join" Gateway and just pick a SequenceFlow at random with which to continue.
This is because the Join-Gateway doesn't evaluate any possible conditions on the outgoing SequenceFlows.

This results in completely unpredictable and possibly dangerous behavior (i.e. starting a nuclear war). 

There are two options on how we can handle this:
a) Treat the Gateway as Split-Gateway, forcing it to evaluate the outgoing SequenceFlows assigned Conditions again. This would effectively cover the `MixedGateway` UseCase as well.
b) Throw an error. 

**NOTE:**
This is an issue with Parallel Gateways as well. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

## Example

<details>
<summary>
:warning: Before creating the issue, click here to expand and follow the guide.
</summary>
<br>
  
1. Be sure to fill out **every** topic presented in this template. 
If a section is not valid or useful for your issue, feel free to remove it.

2. Use the attached Checklist to make sure your issue contains all relevant information.

3. Attach a label to your issue that reflects what your issue is all about.
**When your issue concerns only a specific platform, be sure to attach the label for that platform!**

4. Please use a fitting emoji at the beginning of your issue title.

Example 1 - Report a bug:
```md
:bug: Something is not working properly
```

Example 2 - Report a performance issue:
```md
:zap: Something is slower than it should be
```

Example 3 - Report a package vulnerability or security issue:
```md
:lock: Package xy produces vulnerabilites
```

```md
:lock: User XY has access to something he shouldn't have
```

Example 4 - Report missing test coverage: 
```md
:white_check_mark: Add tests for...
```

You can of course phrase your titles however you like.
Just be sure they are short, to the point and convey the general idea of the issue you are experiencing.
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your Issue with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

**Comment by roblen45** [comment]
I think a Join Gateway having more than one outgoing sequenzflow  contradict our style guide.

**Comment by ElRaptorus** [comment]
@roblen45 True, but the handler still needs to be able to recognize and handle this type of misconfiguration.
Right now it just picks a SequenceFlow at random, leading to completely unpredictable behavior.
