### ISSUE TITLE
🐛Parallel Join GW does not Merge Token correctly

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/process_engine_runtime#152]
## Describe your issue

The token after a parallel join does not contain the infos of the previous flow nodes.

I tested this:

<img width="1412" alt="screenshot 2018-11-19 at 09 43 04" src="https://user-images.githubusercontent.com/4034128/48695493-8f58dc80-ebdf-11e8-8324-26517d504365.png">

<img width="1412" alt="screenshot 2018-11-19 at 09 43 12" src="https://user-images.githubusercontent.com/4034128/48695490-8ec04600-ebdf-11e8-961e-259457dfb7a0.png">

As you can see, the token does not contain the `process_engine_toggl_path` variable:

<img width="1412" alt="screenshot 2018-11-19 at 09 43 07" src="https://user-images.githubusercontent.com/4034128/48695491-8f58dc80-ebdf-11e8-98ed-52e7f0d00d4c.png">

## How can others reproduce the issue?

Please talk to me.

## Possible solution

Merge the Token correctly.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@ElRaptorus I thought so, too. 

Looking foward to see this fix.

**Comment by ElRaptorus** [comment]
@cmg-dev Me too. @SteffenKn will handle this. :wink:
