### ISSUE TITLE
✨Get process definitions by correlationId

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#16]
We want to implement a new feature were we can inspect a diagram and how it "looked" when it was started. NOT how it looks right now.

To implement this new feature we need a way to get these diagrams through the corresponding CorrelationId.

This doesn't need to be a complete versioning of all diagrams. But we need a way to trace back how diagrams looked when they were started even if this was 2 months ago.

**Comment by ElRaptorus** [comment]
@cmg-dev @roblen45 
At first glance I'd suggest introducing a new repository (maybe `correlations.repository.sequelize`) where can store the correlation id and a copy of the process model's xml code.
That way we could easily implement the feature and keep the process-model database clean.
