### ISSUE TITLE
🐛 Typing error with ExternalTaskApiClient/ExternalTasksContracts

### ISSUE THREAD

**Issue by LeoTT** [process-engine/process_engine_runtime#167]
#### Describe your issue
This code:
```ts
import {HttpClient} from '@essential-projects/http';
import {
  ExternalTaskApiClientService,
  ExternalTaskApiExternalAccessor,
  ExternalTaskWorker,
} from '@process-engine/external_task_api_client';
import {
  IExternalTaskApi,
  IExternalTaskResult,
  IExternalTaskWorker,
} from '@process-engine/external_task_api_contracts';


const httpClient: HttpClient = new HttpClient();

httpClient.config = {
  url: 'http://localhost:8000',
};
const externalAccessor: ExternalTaskApiExternalAccessor = new ExternalTaskApiExternalAccessor(httpClient);
const externalTaskAPIService: IExternalTaskApi = new ExternalTaskApiClientService(externalAccessor);
```
... causes the following error (due to the last line):

```
../node_modules/@types/node/index.d.ts(7266,88): error TS2304: Cannot find name 'Symbol'.
test.ts(20,7): error TS2322: Type 'ExternalTaskApiClientService' is not assignable to type 'IExternalTaskApi'.
  Types of property 'fetchAndLockExternalTasks' are incompatible.
    Type '<TPayloadType>(identity: IIdentity, workerId: string, topicName: string, maxTasks: number, longPo...' is not assignable to type '<TPayloadType>(identity: IIdentity, workerId: string, topicName: string, maxTasks: number, longPo...'. Two different types with this name exist, but they are unrelated.
      Type 'Promise<ExternalTask<TPayloadType>[]>' is not assignable to type 'Promise<ExternalTask<TPayloadType>[]>'. Two different types with this name exist, but they are unrelated.
        Type 'ExternalTask<TPayloadType>[]' is not assignable to type 'ExternalTask<TPayloadType>[]'. Two different types with this name exist, but they are unrelated.
          Type 'ExternalTask<TPayloadType>' is not assignable to type 'ExternalTask<TPayloadType>'. Two different types with this name exist, but they are unrelated.
            Property 'processModelId' is missing in type 'ExternalTask<TPayloadType>'.
```

Found out that there are two different versions of ExternalTask.
- myproject/node_modules/@process-engine/external_task_api_client/node_modules/@process-engine/external_task_api_contracts/dist/data_models/
- myproject/node_modules/@process-engine/external_task_api_contracts/dist/data_models/

Nested one should obviously not exist.

#### How can others reproduce the issue?

Install the imported packages anywhere, make a file with the codeexample from above and run `tsc filename.ts`.

#### Possible solution

Pretty sure the nested node_modules situation happens when there is a version mismatch.
I assume `external_task_api_contracts` just needs to be upped in `external_task_api_client`.
Have not yet followed up on that, but I intend to.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

## Example

<details>
<summary>
:warning: Before creating the issue, click here to expand and follow the guide.
</summary>
<br>
  
1. Be sure to fill out **every** topic presented in this template. 
If a section is not valid or useful for your issue, feel free to remove it.

2. Use the attached Checklist to make sure your issue contains all relevant information.

3. Attach a label to your issue that reflects what your issue is all about.
**When your issue concerns only a specific platform, be sure to attach the label for that platform!**

4. Please use a fitting emoji at the beginning of your issue title.

Example 1 - Report a bug:
```md
:bug: Something is not working properly
```

Example 2 - Report a performance issue:
```md
:zap: Something is slower than it should be
```

Example 3 - Report a package vulnerability or security issue:
```md
:lock: Package xy produces vulnerabilites
```

```md
:lock: User XY has access to something he shouldn't have
```

Example 4 - Report missing test coverage: 
```md
:white_check_mark: Add tests for...
```

You can of course phrase your titles however you like.
Just be sure they are short, to the point and convey the general idea of the issue you are experiencing.
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your Issue with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

**Comment by ElRaptorus** [comment]
> Pretty sure the nested node_modules situation happens when there is a version mismatch.

@LeoTT That would be my guess as well.
But I can't quite see yet where it occurs.

What versions of the `ExternalTask` packages are you using? 
All of them are currently in a `1.0.x` version and since we use `~`-type versioning for the contracts in all of them, a mismatch should not happen; at least not for the most recent versions.

**Comment by LeoTT** [comment]
My bad, forgot to properly remove them from the package.json before reinstall and used the old ones.
Latest version show no typing errors, I will therefore close this.
