### ISSUE TITLE
A User Task without a Form Field will not be finished

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#18]
#### Describe your issue

If you create a simple diagram with a User Task but leave the Form Fields empty and start it, the User Task will render, of course with out an input field, but on clicking continue it not gets finished.
The server responds with:

<img width="621" alt="bildschirmfoto 2018-08-27 um 09 21 32" src="https://user-images.githubusercontent.com/17248802/44646283-cbaedf00-a9da-11e8-8022-2270a1f96866.png">

#### How can others reproduce the issue?

Import this diagram in BPMN-Studio and start it:

[test.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/2322794/test.bpmn.zip)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Ah, yes, this is actually a designed behavior of the consumer api. 
If you try to finish a user task without setting any form fields it will fail.
At the time the api was first drafted, this was decided to be the desired behavior for that function.

I'll change it with the next `Consumer Api Core` update.
