### ISSUE TITLE
✨ Boundary Events Should Have a TokenHistory

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/process_engine_runtime#187]
#### Describe your issue

Currently boundary events do not have a token history. This makes it really hard to find out if a boundary event was used or not in the live execution tracker of the BPMN-Studio.

For that reason, boundary events should get a token history.

#### How can others reproduce the issue?

- **Have a look at https://github.com/process-engine/bpmn-studio/issues/1198**

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@SteffenKn 
This is very easy to implement. 
You just need to add the following calls at the proper places in the BoundaryEvent handlers:
```ts
await this.persistOnEnter(token);
await this.persistOnExit(token);
```

If you like, you can do this by yourself. 😉 
/cc @alexanderkasten @Vyperus

**Comment by SteffenKn** [comment]
I can do this on monday since i did not see this till now.

**Comment by robpal94** [comment]
Are BoundaryEvents persisted in the `flowNodeInstance` Table? If not, the `persistOn...()` method would fail.

**Comment by ElRaptorus** [comment]
@robpal94 Right now they are not persisted anywhere.
But yes, they would be stored in the same table as all the other FlowNodeInstances.

Wouldn't make much sense to separate them.

**Comment by ElRaptorus** [comment]
@SteffenKn Any news on this issue?

**Comment by SteffenKn** [comment]
I started once, but I didn't really get very far because other things came up. This PR was created, but it is far from working: https://github.com/process-engine/process_engine_core/pull/220
