### ISSUE TITLE
🚫 ♻️ Cyclic Jobs do not accept ISO8601 or cron Syntax

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#196]
#### Describe your issue

This is more a question then an actual bug report, but how is the syntax for `cyclic` Timer events? 
According to the bpmn - spec, a cyclic Timer Event can be defined like so: 
```
R3/PT10H
``` 

or with the cron syntax, like so: 
```
0 0/5 * * * ?
```

But none of these seems to actually work. We only get the following error: 
```
Error: an error occured during job scheduling
```

This may be, because in the Timer implementation (timer_facade.ts), we are just passing the value from the `Timer Definition` Field to ´moment.duration`  as an input value: https://github.com/process-engine/process_engine_core/blob/develop/src/runtime/engine/timer_facade.ts#L96

The problem with this is, that `momentjs Durations` accept every input, even, if its not supported. (`momentjs just interprets invalid durations as a duration which takes 0 Seconds). 

My question now is:
* Do we **really** support cron like job cycles? 
In the `TimerService` we are actually using a Library which can handle this sort of things. But since we pass the `timerValue` through moment, all informations will be lost and the `node-schedule` library does not know what to do. 

See: https://github.com/essential-projects/timing/blob/develop/src/timer_service.ts#L113

* If we actually support cyclic timers, whats the right syntax for them?

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
So I found this line: https://github.com/process-engine/process_engine_core/blob/develop/src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_timer_catch_event_handler.ts#L118 which tells me, that _cyclic Timers_ are currently unsupported.
But if this is the case, why does the `TimerFacade` and the `TimerService` expose a method, when lets you run periodic/cyclic timers?

**Comment by ElRaptorus** [comment]
@robpal94 The TimerFacade and the TimerService it uses were taken from the old implementation, which supported cyclic timers.
We can't do that yet, because of the way we handle FlowNodeInstances.
This will require some major refactoring though and I don't know when this will be done.

As far as I know, this hasn't actually be a required UseCase yet, can you tell me what you need this for?

**Comment by ElRaptorus** [comment]
Blocked by https://github.com/process-engine/process_engine_runtime/issues/197

**Comment by robpal94** [comment]
> As far as I know, this hasn't actually been a required UseCase yet, can you tell me what you need this for?

I don't really need cyclic timers but to solve this issue (https://github.com/process-engine/process_engine_runtime/issues/195) its kinda necessary to know, how we can verify cyclic timer definitions (or if we just refuse to accept a ProcessModel which contains a cyclic timer definition, since we don't support them yet).

**Comment by robpal94** [comment]
@ElRaptorus and I discussed, that we currently do not support such TimerDefinitions. Therefore, its not necessary to do any kind of validation for them.
