### ISSUE TITLE
✨Get ProcessInstances for ProcessModel

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#20]
#### Describe your issue

For the new Inspect Dashboard feature we need a function in the Management Client that gets all ProcessInstaces for a given ProcessModelId.

Informations we need are:

- diagram_xml: The xml of the diagram as it was when the process started.
- started_at: The timestamp when the process started.
- status: The status of the process. (Running, Stopped, Waiting, Terminated etc.)
- user: The User that started the ProcessInstance.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@Vyperus 

> diagram_xml: The xml of the diagram as it was when the process started.

If this is a requirement, then this is currently blocked by #16 

> user: The User that started the ProcessInstance.

This is currently not possible. We can store a users identity, but as of yet there is no way that I am aware of, on how to associate that identity with a concrete user. AFAIK there isn't even a concept for this for the iam service (correct me if I'm wrong, @cmg-dev @roblen45 )

What we _could_ do, is to return the users auth token to you. Dunno if this might be of benefit to you?

**Comment by robpal94** [comment]
Is this still needed or an open issue? @Vyperus @ElRaptorus

**Comment by ElRaptorus** [comment]
Nope, not an issue anymore.
