### ISSUE TITLE
✨ Implement `interrupted` state for FlowNodeInstances

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/process_engine_runtime#235]
#### Describe your issue

We need a new `interrupted` state for FlowNodeInstances, to account for BoundaryEvent related interruptions.

For example when running this diagram:

<img width="742" src="https://user-images.githubusercontent.com/20394992/52344525-46b10280-2a1b-11e9-8b51-e048472c7b1a.png">

Even if the ManualTask gets interrupted by the BoundaryEvent, it will still be put in a `finished` state.

As a consequence, the BPMN-Studio's LET will always mark it as green, because it considers this task to have finished without interruption.

For this, we need the new `interrupted` state.

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Currently blocked by this:
https://github.com/process-engine/process_engine_runtime/issues/197

This issue will introduce some major changes to the handling of BoundaryEvents (for instance, we will finally be able to use both interrupting and non-interrupting BoundaryEvents), so I'd recommend to not work on this until that refactoring is done.

**Comment by ElRaptorus** [comment]
Some issues with the base FlowNode handlers came up during the implementation of this.

This issue is frozen, pending a wider refactoring of the FlowNode handling.

**Comment by ElRaptorus** [comment]
This issue is put on ice, until the AtlasEngine sees the light of day.
It will be implemented for that engine only.
