### ISSUE TITLE
🐛 Can't parse diagram with cyclic timer event

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#237]
Taken from: https://github.com/process-engine/process_engine_core/issues/240

#### Describe your issue

If you try to deploy a diagram with cyclic timer event, the parser throws an error.

#### How can others reproduce the issue?

See the linked issue.

#### Possible solution

As discussed in the referenced issue, we will loosen the restrictions on the diagram deployment, so that it becomes possible to deploy diagrams with cyclic timers, if at least one other StartEvent without such a timer is present.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by robpal94** [comment]
Processes which contain at least one normal StartEvents are passed through with the current Core Release. As soon as the new Runtime Version gets release, this issue can be closed.

**Comment by ElRaptorus** [comment]
Fixed with the Relase of v5.5.0.
