### ISSUE TITLE
🐛 Using the HttpClient to query a non-responsive uri causes the ProcessEngine to freeze

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#239]
#### Describe your issue

When using the internal HTTP-Client to query a non-existing uri, the ProcessEngine freezes. 

There are two scenarios where this happens:

* When querying an HTTP Endpoint, which returns with an empty response:
Here, the ProcessEngine throws the following Error: 

```sh
scripts/vendor-bundle.js:1408 Unhandled rejection InternalServerError: Cannot read property 'val' of undefined
    at HttpFetchClient.<anonymous> (file:///Applications/bpmn-studio.app/Contents/Resources/app.asar/scripts/app-bundle.js:3474:39)
...
```

In this state, its also not possible to retrieve the UserTask list. It just throws this error over and over again until the DataStore is deleted. 

* When trying to query an Endpoint which does not exist:
The ProcessInstance just hangs. There is no sort of Timeout or `Connection Refused` Message. 

#### How can others reproduce the issue?

* Deploy and Execute this Process: [HTTP REST API.bpmn.txt](https://github.com/process-engine/process_engine_runtime/files/2841848/HTTP.REST.API.bpmn.txt)
* See, that the error written above is thrown
* Create a new Process with a HTTP Service Task
* Set an invalid URL and execute that Process
* See, that the ProcessEngine hangs on this Process

#### Excpected Behavior

The ProcessEngine should cancel the current running ProcessInstance and/or throw an error which describes, that the requested HTTP Endpoint does not answer.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Are you sure this is related to the runtime and not the HttpClient you use with the studio? 
By default express returns a `404 Cannot GET/PUT/POST/etc`. 

But it never hangs. You can try that out for yourself by starting the runtime and manually running requests against non-existent routes against it.

We should take a closer look at this tomorrow.

**Comment by ElRaptorus** [comment]
@robpal94 Btw, `HttpFetchClient` looks like that client you use with the studio. 
Are you **really** sure, that this isn't more of an issue with that client?

**Comment by ElRaptorus** [comment]
After conferring with @Vyperus I finally understand what your issue is. 

@robpal94 Really, please try to be more precise when formulating them. I can only help you with your issus, if I know what they even are. 

I'll close this issue in favour of this one: https://github.com/process-engine/process_engine_runtime/issues/240
