### ISSUE TITLE
♻️ Parallel Join-Gateways should store all "previousFlowNodeInstanceIds" from incoming flows

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#245]
#### Describe your issue

All FlowNodeInstances store the instance ID of the FlowNodeInstance that came before them. 
However, for `ParallelJoinGateways`, this should be a list, because they will always have multiple FlowNodeInstances that were executed before them.

#### Possible Solution

Refactor `ParallelJoinGateways` so that they can store multiple `previousFlowNodeInstance` values.

This could be a little tricky in terms of persistence, because the `previousFlowNodeInstanceId` is always set during the `onEnter` state change (as it must be, otherwise reconstructing ProcessInstance paths will not work).

However, the Gateway cannot know all previous FlowNodeInstances at the time it was first called. 
That will only be the case after the last incoming branch was resolved and the `onExit` state change happens.

The only somewhat viable solution I can think of would be to allow the `onExit` state change to optionally apply a new value for `previousFlowNodeInstanceId`. 
But that could be dangerous, if any FlowNodeHandler other than the ParallelJoinGateway makes use of this.

Since we do not actually use that `previousFlowNodeInstanceId` anywhere yet, this is of a somewhat low priority.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
@ElRaptorus Wäre es eine Idee, die `previousFlowNodeInstanceId` wegzuschmeißen?

**Comment by ElRaptorus** [comment]
Ich werde nochmal verifizieren ob die irgendwo benutzt wird, aber an sich ist das denke ich eine gute Idee.

**Comment by ElRaptorus** [comment]
@rrrene Aktuell wird diese ID noch gebraucht um Prozesspfade wiederherzustellen, die über BoundaryEvents gelaufen sind. 
D.h. aktuell können wir diese ID nicht entfernen.

Das wird sich aber ändern, wenn wir den `interrupted` state bekommen. 

Auf die Gateways sollte das aber keine Auswirkungen haben, da diese keine BoundaryEvents besitzen.

Ich denke man kann dieses Issue hier dann eher schließen und stattdessen ein Follow-Up Issue für #235 erstellen, welches dann das Entfernen dieser ID festhält.

//cc @SteffenKn

**Comment by ElRaptorus** [comment]
No longer low priority, because another bug has come up with the resumption of ProcessInstances.
See #332
