### ISSUE TITLE
♻️ StartEventIds should be optional, when starting ProcessModels with only one StartEvent

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#252]
#### Describe your issue

Currently, we always need to provide a StartEventId, when starting new ProcessInstances.
Since there are a lot of ProcessModels that only make use of one such event, we should consider making that parameter optional.

If an attempt is made to start a ProcessModel with multiple StartEvents, that parameter must still be supplied, naturally.
Not doing so must result in an error, preferably caused by the `ExecuteProcessService`.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by demdh** [comment]
If multiple start events are provided, but only one of them is untyped, you should pick that one.

**Comment by moellenbeck** [comment]
@demdh ich glaube das ist dann zuviel implizite Magic. Wie im Ticket finde ich die Lösung fürs werde in Ordnung.
