### ISSUE TITLE
✨ Support File Upload for UserTasks

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#254]
#### Describe your issue

A Feature-Request has been made to allow file uploads with UserTasks.

To realize this, we must implement a new API for handling File Uploads (probably in the Consumer Domain?).

This API must be able to receive files and store them locally - either in a database or directly somewhere within the filesystem - and also to retrieve them.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by rrrene** [comment]
@ElRaptorus Lass uns hier mal mit den Kollegen vom Team Susi sprechen :+1: /cc @Vyperus @roblen45 @cmg-dev
