### ISSUE TITLE
🐛 Send mail service does not work

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#28]
#### Describe your issue

When trying to use the send mail service with the Windows Version, the ProcessEngine
throws the following StackTrace: 

```
-- An unhandled exception was caught! Error: --
{ Error: spawn sendmail ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn sendmail',
  path: 'sendmail',
  spawnargs:
   [ '-i',
     '-f',
     'mailservice@process-engine.io',
     'robin.pal@hotmail.de' ] }
-- end of unhandled exception stack trace --
```

**Update:** This issue also affects macOS and linux now.

Trying to send emails produces the above error.

On macOS the following error message is thrown: 

```
Error: Sendmail exited with Exit Code 1
```

_Note: On macOS this is always reproducable when entering an invalid email address._ 

#### How can others reproduce the issue?

* Try to execute [this process](https://gist.github.com/robpal94/236abfe70305dc812f4ebe787820ff9e)
* Look at the logs

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@robpal94 If you have the time to investigate this, feel free to do so. 🙂

**Comment by robpal94** [comment]
We need to discuss, if we will support this feature in the future.

**Comment by ElRaptorus** [comment]
@cmg-dev @moellenbeck @roblen45 Do you have any info about this?

**Comment by robpal94** [comment]
You're right. The service seems to work again (seems the curse which disabled the MailService was revoked).
