### ISSUE TITLE
 🐛 Management Api Client needs node-uuid but doesn't have a dependency on it.

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#288]
#### Describe your issue

I was debugging something in the Studio when i cam up with this log output:
<img width="397" alt="Bildschirmfoto 2019-03-09 um 10 56 51" src="https://user-images.githubusercontent.com/17248802/54069838-10091a80-425b-11e9-98b8-49181187d949.png">

It seems like the external accessor has a dependency on `node-uuid` but the package.json  of the `management_api_client` doesn't.

I wrote more on this here:
https://github.com/process-engine/bpmn-studio/pull/1352

#### Possible solution

Add it as a dependency.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Which version of the client are you using?

Because the most recent version has `node-uuid` as a dependency. As I recall, it was added some time ago, when we kicked out `uuid` everywhere.

See here: https://github.com/process-engine/management_api_client/blob/develop/package.json#L26

**Comment by ElRaptorus** [comment]
@Vyperus 
I just checked the `solutionexplorer.repository.management_api` package and found this little gem:

https://github.com/process-engine/solutionexplorer.repository.management_api/blob/develop/package.json#L19

You really should consider updating the client to v4.1.0 😉

**Comment by ElRaptorus** [comment]
I'm going to close this, since this is obviously not an issue with the backend.
