### ISSUE TITLE
✨ Add `onProcessModelDeployed` notification

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#316]
#### Describe your issue

To avoid polling for new ProcessModels, it would be nice if there was an event such such as `onProcessModelDeployed`, which gets triggered, when a new ProcessModel (which is also visible for the logged in user) was deployed. 

#### Possible solution

Add an event which is triggered, when a new ProcessModel was deployed to the ProcessEngine. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
Sounds like a good idea in principal. 

But I wouldn't remove the polling entirely. BPMN Studio should implement a complementary `refresh` function that allows a user to manually poll the list.

There is also the question on what happens, if the user models a lane on the ProcessModel that he is not allowed to access.
Right now this always permitted on deploy, but the lane gets filtered out when querying that ProcessModel.

Also keep in mind that the BPMN Studio currently uses the dummy token for every `GET ProcessModel` request, so there really isn't any identity related filtering happening here.

These issues must be addressed before we can add such a notification.

**Comment by Vyperus** [comment]
@ElRaptorus We are not talking about only BPMN-Studio here ;) Whether or not to use polling is entirely up to the Application using the Consumer API. 

You should be able to check if a User with given Identity would be able to "see" a ProcessModel if he is querying for it (i.e. check if he can "get" it, if yes, he can deploy it).

I don't see why the specific implementation in BPMN-Studio is a problem here.

**Comment by ElRaptorus** [comment]
> We are not talking about only BPMN-Studio here

But such a change would also affect the Studio, because this check:

> You should be able to check if a User with given Identity would be able to "see" a ProcessModel if he is querying for it (i.e. check if he can "get" it, if yes, he can deploy it).

doesn't exist yet.

**Comment by Vyperus** [comment]
Ok so lets say if the Studio is using the "dummy_token" anyway the User of the Studio would be able to see the diagram/process anyway.

If he/she then logs in and doesn't "get" the diagram anymore this is IMO the expected behavior.

So if I'm right then adding this check wouldn't affect the Studio at all.

**Comment by ElRaptorus** [comment]
But that in turn enforces the need to check if the user is attempting to deploy a diagram that has already been deployed by another user (which can easily happen, if the user doesn't see all deployed ProcessModels). 
That is also a check that doesn't exist yet.

We don't even store the users identity with the ProcessModel. 
That too is something that needs to be changed. 

I really think these issues need to be addressed before we start fiddling around with additional notifications.
