### ISSUE TITLE
✨ Timer Event: Should start Timers with a past date immediately

### ISSUE THREAD

**Issue by demdh** [process-engine/process_engine_runtime#337]
## Description
Date definitions for timer events must not be in the past.
This means that, for calculated times, it must always be ensured in advance that the time is not in the past. 

## Reproduction
The attached process simulates an hysteresis function. It should guarantee that the 'Do Stuff' task will be executed at most once a minute. If the execution of the task takes longer than a minute, the calculated next start time will be in the past. The task should then be executed immediately.

[Hysteresis.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3198141/Hysteresis.bpmn.zip)

## Possible solution
Remove this constraint.

**Comment by ElRaptorus** [comment]
This is not a bug, but expected behavior. 

I will note this as a feature request.

**Comment by ElRaptorus** [comment]
@demdh This is implemented in #339
