### ISSUE TITLE
🐛 Cannot set authority via environment

### ISSUE THREAD

**Issue by Paulomart** [process-engine/process_engine_runtime#340]
## Description

If you try to set the authority via environment it fails.

## Reproduction

```bash
export iam__iam_service__basePath="http://this-is-my-host.com"
npm start
curl http://localhost:8000/security/authority
```

See that the authority is still the default.

## Possible solution

Also evaluate the environment in this function:

https://github.com/process-engine/process_engine_runtime/blob/cc0c33d7b09004165f631a027f84e19626973f6f/src/global_route_configurator.ts#L64-L76

Currently only the config is loaded; No environment variables are considered.

**Comment by ElRaptorus** [comment]
Nice catch.

**Comment by ElRaptorus** [comment]
Fixed in https://github.com/process-engine/process_engine_runtime/commit/29ed811e45cfd1fd990af67450793257b9da0426#diff-438bc859645cde9c946ffc46e38eef9dR49

Will be shipped with the next release.
