### ISSUE TITLE
♻️ ExternalTask logs should display calculated payloads 

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#352]
## Description

The ExternalTask logs always the token.current in onSuspend, even if a user defined payload is 
configured.

I think in this case it should write the calculated payload instead.
This make it much easier to see the real request given to the ExternalTask.

## Reproduction

Create a diagram with an ExternalTask and specify a payload.

**Comment by ElRaptorus** [comment]
@roblen45 Can you provide a Log sample? 
Neither the ExternalTaskHandler, nor the ExternalTask API log any kind of token, so I'm having a little difficulty finding the location of the log you are referring to.

**Comment by roblen45** [comment]
> @roblen45 Can you provide a sample log?
> Neither the ExternalTaskHandler, nor the ExternalTask API log any kind of token, so I'm having a little difficulty finding the location of the log you are referring to.

@ElRaptorus 
The normal onSuspend log message of the ServiceTask logs the current token.

**Comment by ElRaptorus** [comment]
Out of curiosity, which version of the Runtime are you using? 

This is the log I get when starting an ExternalTask with a payload:

![Bildschirmfoto 2019-06-24 um 14 11 58](https://user-images.githubusercontent.com/15343316/60017888-244a1980-968a-11e9-95a3-80e3a6baaaec.png)


I don't see any logged tokens.

**Comment by ElRaptorus** [comment]
@roblen45 
Fixed in #356
