### ISSUE TITLE
✨ Persist technical logs in logfiles

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#357]
## Description

This concerns the logs we print out to the console.
Since these are technical logs, they do not get persisted with the ProcessModel's standard log files, which only contain professional logs for the ProcessModel.

When doing remote-support it would be very helpful if these technical logs were persisted as well, so that the user in need could send them over.

## Possible solution

We are using `loggerhythm` for printing out these logs to the console. Loggerhythm is wrapped around `winston`, which AFAIK allows for multiple transports, including a file transport. 

We should investigate on what it would take to add a new transport to `loggerhythm`, which will print out these technical logs into a file. 

If that should not prove possible, we need to come up with some other solution for this problem.

Maybe with a logger of our own?

**Comment by ElRaptorus** [comment]
I conferred with @heikomat and we can't just add a transport to loggerhythm in its current implementation.

But we can create a fork and add that transport ourselves.

/cc @rrrene

**Comment by heikomat** [comment]
Just a hint:
According to [12-factor logs](https://12factor.net/logs), the handling of logs is not something the application that produces the logs should do. In a best-case scenario, the app just prints everything to `stdout`, and the logs are then piped to a file or sent to some other tooling by whoever started the application

**Comment by rrrene** [comment]
@heikomat Wichtig ist der Kontext: Das BPMN Studio läuft bei Kunden als EXE-Datei. Wir haben aktuell keine vernünftige Methode an die Logs des Hauptthreads zu kommen (wo die PE und die OpenID-Geschichten laufen). Im Rahmen von Ferndiagnosemöglichkeiten binden wir uns dadurch einen Arm auf den Rücken und schwächen unser Produkt.
