### ISSUE TITLE
✨ Add onProcessWithProcessModelIdEnded Event

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_runtime#369]
## Description

Currently, the only event which can be set up to fire only for a specific ProcessModelId is the `onProcessWithProcessModelIdStarted()` event. It would be nice, if there where an `onProcessWithProcessModelIdEnded()` counterpart.

**Comment by ElRaptorus** [comment]
Actually, I've been questioning the validity of the `onProcessWithProcessModelIdStarted`. 

I'd like to keep the notifications as generalized as possible and leave it up to the end user to decide which notifications he wishes to process and which he doesn't. 

This notification clearly doesn't fit the bill, so I'm not convinced that implementing yet *another* such dedicated notification is something I want to do.

/cc @rrrene

**Comment by rrrene** [comment]
@robpal94 Vielleicht erläuterst du den Use-Case ein bisschen? 

Ich denke, es macht wenig Sinn, wenn wir blind alle denkbaren Events und Filterungen für Events aus der Engine heraus als fertig aufbereitete Events emitten, ohne die Anwendungsfälle dahinter zu verstehen. Sonst bekommen wir schnell `onProcessModelStartedWithIdentityHavingClaimForProcessInstanceIdMatchingTheFollowingClosure`,  das wir dann auf unbestimmte Zeit supporten müssen. 😱  :+1:

**Comment by robpal94** [comment]
Mein Gedankengang war der, dass ein Client, welcher sich auf zum Beispiel auf ein `onProcessFinished()` Event subscriped, nicht ständig für jeden Prozess eine Benachrichtigung erhalten muss, obwohl dieser nur an einem Prozess mit einer bestimmten Prozess Model Id interessiert ist. Aktuell muss der Client bei jeder Benachrichtung selber herausfinden, ob er sich für die Benachrichtigung interessiert, oder nicht. 

Woran ich aber nicht gedacht habe: Werden die Events nur für das Ende eines Prozesses für eine gegebene Identity versendet? Falls ja, wäre der Issue in der Tat nicht so relevant.

**Comment by ElRaptorus** [comment]
Da wäre meine erste Frage:

> nicht ständig für jeden Prozess eine Benachrichtigung erhalten muss

Sofern das bei euch nicht die Performance beeinträchtigt (wofür schon echt verdammt viele Notifications zusammenkommen müssten), sehe ich da ehrlich gesagt kein Problem.

> Werden die Events nur für das Ende eines Prozesses für eine gegebene Identity versendet?

Nein.

Mein Problem ist nach wie vor, dass ich nicht jeden anwendungsspezifischen UseCase ausimplementieren will. @rrrene hat das sehr gut zusammengefasst, wenn wir diese Tür einmal öffnen, dann sind wir schnell bei mehr Notifications als man maintainen kann (oder überhaupt sollte).
Eigentlich war die `onProcessWithProcessModelIdStarted` notification schon zu viel.

Die ProcessEngine sollte nur allgemeine Notifications für ihre UseCases bereit stellen und es dem Anwender selbst überlassen, mit welchen Notifications er was anfangen will und mit welchen nicht. 
Da zählen mMn Notififations für spezielle Prozessmodelle mit dazu.
