### ISSUE TITLE
✨⚡️ Provide endpoint for querying all active ProcessInstances

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#377]
## Description

There are situations where it would be useful to have all currently active ProcessInstances handy.

It would remove the need for querying every ProcessInstance individually, which would be quite a boon when dealing with huge amounts of ProcessInstances.

See this issue here:

https://github.com/process-engine/bpmn-studio/issues/1594#issuecomment-515881340

## Solution

Implement a new UseCase for the Management API, which allows a User to request all active ProcessInstances.

**Comment by rrrene** [comment]
*Falls* ich es richtig verstehe, holen wir im Moment im ersten Schritt alle Prozessinstanz-Ids und dann in einem zweiten Schritt für jede Instanz die "Infos". 

Ich fände es daher noch vielseitiger, wenn wir dem neuen Use-Case/Endpoint die Prozessinstanz-Ids geben könnten, zu denen wir die Infos haben wollen. Dann hätten wir die Freiheit, zunächst wie vorher alle Prozessinstanz-Ids dorthin zu schicken, aber später Windowing für die Pagination im Client zu implementieren und nur X auf einmal abzufragen.

Meinungen?

**Comment by ElRaptorus** [comment]
> _Falls_ ich es richtig verstehe, holen wir im Moment im ersten Schritt alle Prozessinstanz-Ids und dann in einem zweiten Schritt für jede Instanz die "Infos".

Fast. 
Das geschieht aktuell über den "GetActiveCorrelations" Call. Daraus werden dann die IDs der laufenden Prozessinstanzen extrahiert und bei Bedarf werden dann zu dieser die Details abgefragt.
 
> _edit_ Vielleicht hätte ich #379 erst lesen sollen 😅

🙃

**Comment by ElRaptorus** [comment]
Hmm wenn ich es mir recht überlege, brauchen wir so einen Query eigentlich garnicht. 

Die relevanten Infos zu den Prozessinstanzen gibts bereits in der Response von dem "GetActiveCorrelations" query. Die Infos stecken eh in der gleichen Tabelle.
Eigentlich sollte es reichen für diesen Query Ranges/Pagination zu implementieren. Damit sollte sich die Performance erheblich verbessern.
