### ISSUE TITLE
🐛 ParallelGateways warten nicht auf alle eingehende Pfade

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/process_engine_runtime#389]
## Description

Sobald zwei Token durch den selben Pfad gehen wird der Prozess beendet.
Scheinbar wird nur auf die Anzahl der Token mit der Anzahl der eingehenden Pfade gecheckt.

![Screenshot 2019-08-12 at 16 38 16](https://user-images.githubusercontent.com/17065920/62873896-7a4d4c00-bd20-11e9-96e3-fe29583a774d.png)

## Reproduction

Siehe Screenshot

[parallelgatewaybug.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3493029/parallelgatewaybug.bpmn.zip)

**Comment by ElRaptorus** [comment]
Das ist tatsächlich so. 

Der Join-Gateway wartet nur, bis die passende Anzahl an Token empfangen wurde, aber checkt nicht gegen, von welchen vorausgehenden FlowNodes bereits Token empfangen wurde. 

Sollte relativ leicht zu fixen sein, da die `ProcessModelFacade` eine Methode `getPreviousFlowNodesFor(flowNode)` bereit stellt, mit welcher sich die FlowNodes, die vor dem Gateway kommen, abfragen lässt.
