### ISSUE TITLE
✨Integrate Payload Field for Call Activities

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#391]
## Description

We noticed that if you want to reuse a diagram (say an edit entity process) you need to declare some sort of interface that if the process gets started needs to be placed inside the token at start. (An ID of an entity that shall be edited for example)

To achieve this you often have to manipulate the token in a ScriptTask before calling the process with a CallActivity.

To make it easier and clearer why this token manipulation takes place it would be nice to have a "Start Token Payload"-Field inside the Property Panel of BPMN-Studio. The PE then can use that as the payload of the token when starting the process via call activity.

Processes can already be started with a start token in BPMN-Studio so this feature would just further enhance this feature.

## Reproduction

I added some processes we are currently working on.
Hopefully they make it a little bit clearer what I mean.

[Archiv.zip](https://github.com/process-engine/process_engine_runtime/files/3508388/Archiv.zip)

**Comment by ElRaptorus** [comment]
I'm not entirely sure I get your meaning.

But:

> ...it would be nice to have a "Start Token Payload"-Field inside the Property Panel of BPMN-Studio. 

Am I correct in assuming that what you want is something for the BPMN Studio?
If so, why not open this issue there?
