### ISSUE TITLE
♻️ Merge Logging- and Metric- APIs

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#429]
## Description

We currently have two APIs that generate different kind of logfiles:
- The Metrics API
- The Logging API

Originally, it was intended to store varying data with each. However, over the course of the past few months, the data each of them stores has become very similar - to the point of almost being duplicates of each other.

Since we are already planning a common log format for the ProcessEngine.ts and the ProcessEngine.NET, we should consider merging the two APIs.

## Possible solution

I think it makes the most sense to keep the `LoggingAPI` and discard the `MetricsAPI`. 
The new Logging API can then use the new format we conceptualized some time ago, so we can be sure it stores every info we need.

The `KpiApi` and the `ProcessEngineCore` can then use the logging service to store & retrieve their data.

**Comment by moellenbeck** [comment]
@ElRaptorus die Idee ist es aber auch das die PE nur noch Events veröffentlich und diese dann in unterschiedliche Datensenken auszuleiten (Logging, Metrics etc).

**Comment by ElRaptorus** [comment]
> @ElRaptorus die Idee ist es aber auch das die PE nur noch Events veröffentlich und diese dann in unterschiedliche Datensenken auszuleiten (Logging, Metrics etc).

Das ist aber wohl eher was für die AtlasEngine.
