### ISSUE TITLE
🐛 Unterschiedliche Rückgabe wenn keine Correlations vorhanden sind

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/process_engine_runtime#432]
## Description

Auf einer ProcessEngine, die mit einem IdentityServer konfiguriert ist, sind drei Prozesse deployed.
Zwei der Prozesse haben keine Correlations. Das sieht man, indem man einen Request macht, der die Correlations für das angegebene Prozessmodell zurückgeben soll. 

Bei einem Prozess (der noch nie Ausgeführt wurde) kommt ein HTTP Status `404` zurück. 

Bei dem anderen Prozess kommt ein Objekt mit `correlations` und `totalCount` zurück. Das Correlations Array ist leer und der `toalCount = 0`. 

Hier sollte normalerweise auch ein 404 Status zurückkommen.

## Reproduction

- starte eine ProcessEngine mit `allowGodToken = false`.
- starte den IdentitySever
- verbinde das 5.8.0 BPMN Studio mit der ProcessEngine
- deploy alle drei Prozesse im Anhang
- warte bis der eine Cronjob gestartet wurde
- führe eines der anderen beiden Diagramme/Prozesse ein paar mal aus, sodass Correlations erstellt werden
- wechsle auf die Inspect-Correlation Ansicht
- Wechsle zwischen den Prozessmodellen/Prozessen/Diagrammen
- In der Network Sektion der Dev Tools sieht man die Response der einzelnen Requests

[Archive.zip](https://github.com/process-engine/process_engine_runtime/files/3681154/Archive.zip)

**Comment by ElRaptorus** [comment]
Eigentlich wäre es sinnvoller, das so anzugleichen, dass bei allen Requests, die nichts zurückgeben und keine bestimtme Correlation abfragen, ein leeres Array zurück kommt.
Das ist auch das Standardverhalten bei allen anderen UseCases (get ProcessModels, get Tasks, etc.).
