### ISSUE TITLE
Clarify naming for "/" route

### ISSUE THREAD

**Issue by rrrene** [process-engine/process_engine_runtime#461]
## Description

Das Wording von `DO_NOT_BLOCK_GLOBAL_ROUTE` finde ich extrem unglücklich.

* Hier wird von der PE aus ihrer Sicht nichts in ihrer Fachlichkeit "blockiert". Wir beschreiben mit diesem Namen vielmehr einen möglichen Schmerz des Endnutzers, der ihn dazu bringen könnte, nach diesem Parameter zu suchen.
* Auch den Ausdruck "globale Route" finde ich nachfragebedürftig (habe ich so als Synonym für "/" auch noch nicht gehört).
* Die Negativ-Formulierung des Parameters finde ich nicht gut. Meiner Meinung nach ist es passender, ein Verhalten abzuschalten, indem man etwas auf `false` setzt (anstatt eine negativ formulierte Variable auf `true` zu setzen).
* Die Tatsache, dass man den Parameter auf irgendeinen Wert setzen kann, finde ich nicht explizit und im krassen Gegensatz zu der sonst üblichen `x === null || x === undefined`-Pedantik.

Ich frage mich, wieso es einen "LASS_DAS"-Parameter gibt und eine hard-codierte Route `/process_engine`. Das ist aus meiner Sicht "technical debt mit Ankündigung".

Wäre es nicht viel passender, wenn ich einfach die Route, unter der alles ausgeliefert werden soll, konfigurieren könnte? Bspw. `PARAMETER_FUER_ROUTE='/my_pe'` und dann trage ich im Studio einfach `localhost:5000/my_pe` ein?

Wir sollten das vor dem Stable-Release klären. 👍

**Comment by ElRaptorus** [comment]
Über den Namen de Parameters kann man sicherlich diskutieren. 

Die `/process_engine` route würde ich jedoch nicht konfigurierbar machen, aus dem einfachen Grund, dass das BPMN Studio dann die PE nicht mehr finden kann. 
Der Sinn hinter diesen Routen ist ja, es dem Studio zu erlauben auf ProcessEngines zugreifen zu können, die in andere Anwendungen embeddet sind (bei denen `/` sehr wahrscheinlich für andere Zwecke benutzt werden wird, als für die Ausgabe der PE Infos).
Wenn ich es dem User nun aber erlaube, diese Routen anders zu benennen, dann hat BPMN Studio keine Möglichkeit mehr, die PE zu finden.
