### ISSUE TITLE
🐛 Parallel Gateways Sometimes Do Not Finish

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/process_engine_runtime#463]
## Description

When running [this](https://github.com/process-engine/process_engine_runtime/files/3761502/Parallel.Test.zip) process multiples times, the parallel gateway does not finish most times.

<img width="1412" src="https://user-images.githubusercontent.com/20394992/67379549-5f515080-f589-11e9-9736-3bb4c2f2067e.png">

## Reproduction

- Run [this](https://github.com/process-engine/process_engine_runtime/files/3761502/Parallel.Test.zip) process multiples times

## My setup

**Runtime v9.0.0**

<img width="512" alt="Bildschirmfoto 2019-10-23 um 11 37 35" src="https://user-images.githubusercontent.com/20394992/67379668-83ad2d00-f589-11e9-9cde-1ac369c0ce32.png">

**Comment by ElRaptorus** [comment]
It is interesting that the `onExit` token was created, but the state of the Gateway remains "running".

Might have something to do with the fact that the tasks arrive at the gateway simultaneously. 

This will probably take some digging.
