### ISSUE TITLE
✨ConsumerAPI should return all UserTasks which the Identity could edit.

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#469]
## Description

The method `getWaitingUserTasksByIdentity` only returns the UserTasks created by a process started by the given identity. 

It would be better to return all UserTasks that the identity could work on. 

## Possible solution

Return all UserTasks in Lanes where the identity has the claim for.

**Comment by ElRaptorus** [comment]
Actually, `getWaitingUserTasksByIdentity` does exactly what it is supposed to. It returns all tasks owned by the given identity (which is what the name implies).

What you describe is a completely separate UseCase. 
We could call this something like `getAccessibleWaitingUserTasks` or something similar.

**Comment by ElRaptorus** [comment]
This is something that will be possible with the AtlasEngine. But we will not implement this for the ProcessEngine.
