### ISSUE TITLE
🐛 TimerIntermediateCatchEvent does not resume

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#473]
## Description

The TimerIntermediateCatchEvent "Warten bis Dienstag abend" does not resume at the expected time.

## Reproduction

See process instance with correlationid 'ac421845-0deb-4001-9ee3-fa8202c5a6af' in the following databases:

[portal_pe_dbs.tar.gz](https://github.com/process-engine/process_engine_runtime/files/3869278/portal_pe_dbs.tar.gz)

Here is a simple reproduction:

[timertest.tar.gz](https://github.com/process-engine/process_engine_runtime/files/3885721/timertest.tar.gz)

This one should wait 10 Seconds.

## My setup

process_engine_runtime 9.1.0

**Comment by ElRaptorus** [comment]
@roblen45 I'm not sure what I'm supposed to observe with the reproduction BPMN, because it works perfectly fine for me.

**Comment by ElRaptorus** [comment]
@roblen45 I just noticed this:

![Bildschirmfoto 2019-11-27 um 15 56 33](https://user-images.githubusercontent.com/15343316/69734017-8e318800-112e-11ea-93c3-fffc4c97a043.png)

Shouldn't that timer definition read: `token.history.calculateTimeToWait.waitUntil`?

**Comment by roblen45** [comment]
> @roblen45 I just noticed this:
> 
> ![Bildschirmfoto 2019-11-27 um 15 56 33](https://user-images.githubusercontent.com/15343316/69734017-8e318800-112e-11ea-93c3-fffc4c97a043.png)
> 
> Shouldn't that timer definition read: `token.history.calculateTimeToWait.waitUntil`?

Yes. You're right.

**Comment by ElRaptorus** [comment]
@roblen45  Ist das hier noch ein Issue, oder haben die Änderungen am Diagramm das Problem gelöst?
