### ISSUE TITLE
✨ Print the used HTTP port on console

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#495]
## Description

The ProcessEngine should be printing the HTTP port it uses on the console when starting up.

This would make it easier for devs to integrate the engine into their own systems, or to connect external ProcessEngines to the BPMN Studio.

**Addendum**:

Furthermore, it should be possible to get infos like Http Port or the current runtime version through simple console commands.

**Comment by rrrene** [comment]
Wichtig: Bitte die Vorgaben [aus der Factro-Aufgabe von August](https://cloud.factro.com?p=task&pi=15b3eaf3-32b1-419d-b33b-20e3363a03a4) beachten:

> Ziel ist es, dass die ProcessEngine-Runtime beim Start loggt, welche Version sie hat und auf welche Adresse sich der HTTP-Endpunkt gebunden hat.
> 
> Die ersten Zeilen des Logs könnten dann bspw. beinhalten:
> 
> ProcessEngine Runtime v9.0.0-alpha.42 starting …
> Running endpoint at 0.0.0.0:4000 (http)
> Running websocket at 0.0.0.0:4001 (ws)
> 
> Ein möglicher Websocket-Endpoint sollte dort auch gelistet sein. Ferner wäre es wichtig, dass dieser Block am Stück erscheint, also nach Möglichkeit NICHT so
> 
> ProcessEngine Runtime v9.0.0-alpha.42 starting …
> [.. 20 Zeilen Info-Logs …]
> Running endpoint at 0.0.0.0:4000 (http)
> [.. 20 Zeilen Info-Logs …]
> Running websocket at 0.0.0.0:4001 (ws)
> 
> Es wichtig, dass wir uns hier in den Nutzer hineinversetzen und seine User Experience verbessern.

**Comment by ElRaptorus** [comment]
> Wichtig: Bitte die Vorgaben [aus der Factro-Aufgabe von August](https://cloud.factro.com?p=task&pi=15b3eaf3-32b1-419d-b33b-20e3363a03a4) beachten:
> 
> > Ziel ist es, dass die ProcessEngine-Runtime beim Start loggt, welche Version sie hat und auf welche Adresse sich der HTTP-Endpunkt gebunden hat.
> > Die ersten Zeilen des Logs könnten dann bspw. beinhalten:
> > ProcessEngine Runtime v9.0.0-alpha.42 starting …
> > Running endpoint at 0.0.0.0:4000 (http)
> > Running websocket at 0.0.0.0:4001 (ws)
> > Ein möglicher Websocket-Endpoint sollte dort auch gelistet sein. Ferner wäre es wichtig, dass dieser Block am Stück erscheint, also nach Möglichkeit NICHT so
> > ProcessEngine Runtime v9.0.0-alpha.42 starting …
> > [.. 20 Zeilen Info-Logs …]
> > Running endpoint at 0.0.0.0:4000 (http)
> > [.. 20 Zeilen Info-Logs …]
> > Running websocket at 0.0.0.0:4001 (ws)
> > Es wichtig, dass wir uns hier in den Nutzer hineinversetzen und seine User Experience verbessern.

Das mit dem Websocket wird so nicht gehen, weil der dynamisch von socket.io gesetzt wird, _nachdem_ der HttpServer initialisiert und der Socket.IO Instanz zugewiesen wurde.
Den kann man also erst ermitteln, _nachdem_ der Bootstrapper alles gestartet hat. 

Ich würde daher vorschlagen, die Portausgaben an das Ende der Logs zu setzen, a la `Now listening for incoming http/socket requests at <your port here>`.
Das macht express z.B. genauso.

Bedenkt man dass sowieso gerne mal viele Logausgaben beim Starten entstehen können, alleine schon durch das Fortsetzen von Prozessinstanzen und dem Ausführen von Migrationen, fände ich es sowieso besser, wenn diese - recht wichtigen - Ausgaben erst nach den Startup Logs kommen, damit der Benutzer diese sofort sieht und nicht erst ggf. durch Meterweise Text hochscrollen muss.

**Comment by ElRaptorus** [comment]
Siehe PR:
Der Port wird jetzt ausgegeben, wenn der Startvorgang abgeschlossen wurde.

Außerdem ist es jetzt möglich sich über Konsolenbefehle Infos wie Version und Http Config ausgeben zu lassen.

**Comment by rrrene** [comment]
siehe Slack
