### ISSUE TITLE
Don't send plaintext responses on JSON endpoints

### ISSUE THREAD

**Issue by rrrene** [process-engine/process_engine_runtime#496]
Marcel hatte neulich einen Bug reportet, der das Logging betraf und den wir bereits gefixt haben.

Eine Begleiterscheinung dieses Bugs war, dass wieder ein HTTP 500 vom Server als plaintext ans Studio ging (anstatt als JSON).

Vielleicht kann @SteffenKn sich das mal angucken, denn wir wirken wirklich unprofessionell, wenn  wir auf Clientanfragen, die explizit nach JSON fragen, mit plaintext antworten. 👍

**Comment by ElRaptorus** [comment]
Closes via #501
