### ISSUE TITLE
🐛 getAllSuspendedTasks liefert 404 

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/process_engine_runtime#512]
## Description

Die Methode `getAllSuspendedTasks` liefert einen HTTP 404 Error mit der Response `{"message":"ProcessInstance with id 62091c71-f0e0-450f-b494-3242d27db471 not found."}`, wenn ich mit einem User eingeloggt bin, der die notwendigen Claims hat um Prozessmodelle zu sehen und auch einen Claim z.B. `Lane` hat, um alle Prozessmodelle und Tasks die sich in einen Prozess mit dem Lanename `Lane` befinden, zu sehen, aber dann Tasks existieren die ich sehen darf, die aber von anderen ProzessInstanzen stammen oder Prozessmodellen, welche ich nicht sehen darf, da ich nicht die richtige Berechtigung habe.

## Reproduction

- zwei Benutzer am IdentityServer erstellen
- erster Nutzer bekommt `can_manage_process_instances`
- zweiter Nutzer bekommt `can_read_process_model ` und `Lane`
- einloggen an eine ProcessEngine mit User 1
- Diagramm mit Tasks (User/Manual/Blank) deploye und ausführen
-  Ausloggen
- einloggen mit User 2
- auf Inspect wechseln
- `There was an error while receiving the tasks.`

## Possible Solution

FlowNodeInstanzen, die von Prozessintanzen anderer User stammen, sollten einfach gefiltert werden und nicht zu einem 404 führen.

## My setup

ProcessEngine 9.3.1
BPMN Studio 5.11.2

**Comment by Paulomart** [comment]
Danke, @alexanderkasten :)

**Comment by ElRaptorus** [comment]
Closes via #516
