### ISSUE TITLE
🐛 "CorrelationId" and "ProcessModelID" on ProcessInstances returned through the ConsumerAPI are switched

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#514]
## Description

ProcessInstances returned through the `ConsumerApi.getProcessInstancesByIdentity` request have their CorrelationId and ProcessModelId switched (i.e. the "CorrelationId" is stored under "processModelId" and vice versa).

## Reproduction

- Request a list of ProcessInstances through the ConsumerAPI's `getProcessInstancesByIdentity` UseCase
- Note how the `correlationId` and `processModelId` properties have been switched.

## Possible solution

Fix it.

**Comment by ElRaptorus** [comment]
@Paulomart  FYI

**Comment by rrrene** [comment]
> Possible solution
> 
> Fix it.

Like aboss

**Comment by rrrene** [comment]
Fat fingers + Handy 🙄

**Comment by ElRaptorus** [comment]
Closed through #514
