### ISSUE TITLE
Slack notification is send before Docker images are built

### ISSUE THREAD

**Issue by rrrene** [process-engine/process_engine_runtime#518]
## Description

[Hier sieht man gut](https://github.com/process-engine/process_engine_runtime/blob/2014ab000c968491a79970563d209ab556809ac9/.github/workflows/continuous-integration-workflow.yml#L485-L502) dass nach der Slack Notification  noch die Docker Images gebaut werden.

@alexanderkasten Wäre es nicht besser, wenn die Slack Notification das Signal für "es ist wirklich *alles* fertig" wäre?

/cc @ElRaptorus

**Comment by ElRaptorus** [comment]
Das ist tatsächlich noch ein Überbleibsel aus der Zeit, bevor die Runtime nach dem Testing noch irgendwas anderes gemacht hat. 

Vor relativ kurzer Zeit wurde nach dem Testen nur noch nach npm bzw. GitHub gepublished und wenn das fehlgeschlagen ist, kam immer eine separate Notification (afaik müsste die auch immernoch kommen).

Aber du hast recht, jetzt wo wir noch Sourcen & Docker Images bauen, kann man das mal so wie du es beschrieben hast ändern. 👍

**Comment by alexanderkasten** [comment]
@rrrene Naja, nicht so ganz.
Die Slack Notification nicht, denn die zeigt wirklich nur den Job Status des Jobs an. Wir haben über GitHub Actions im Moment keine Möglichkeit in einem anderen Job über den Context, auf Informationen und vor allem den State eines vorherigen Jobs zuzugreifen.

Da also das GitHub Release und das Docker Image bauen und publishen und das Publishen auf npm parallel läuft, macht es keinen sinn den/die Slack Steps in den Docker Job zu verschieben.
Wir können so erstmal nicht sagen wann alle der drei Jobs fertig sind.

**Comment by alexanderkasten** [comment]
Wir könnten noch einen Job für das Announcen der Releasenotes hinzufügen, der dann auf Docker, npm und GitHub Release wartet.

**Comment by ElRaptorus** [comment]
Ich glaube, da wir jetzt eh beim Umzug auf die AtlasEngine in den finalen Zügen sind, würd ich hier keinen Effort mehr investieren. 
So wahnsinnig wichtig ist das hier denke ich auch nicht.

**Comment by rrrene** [comment]
Bitte so machen, wie Alex skizziert hat. 

Das Announcen des Releases vor Fertigstellung ist doch blanker Unsinn. Ich muss mich doch drauf Verlassen können, dass das Release da ist, wenn in Slack steht „das Release ist da“!
