### ISSUE TITLE
🐛ConsumerAPI liefert nicht alle meine UserTasks

### ISSUE THREAD

**Issue by roblen45** [process-engine/process_engine_runtime#521]
## Description

Die Route "/api/consumer/v1/user_tasks/own" der ConsumerAPI liefert nur die UserTasks, welche durch von mir gestartet Prozesse erzeugt wurden.

## Reproduction

[MassagePlanen.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/4214994/MassagePlanen.bpmn.zip)

Zwei Benutzer A und B mit dem Claim "Massage Orga".
A startet den Prozess. A kann die UserTask sehen, B nicht.

Gilt auch für ManualTasks.

## My setup

Runtime: 9.4.1

**Comment by ElRaptorus** [comment]
Eigentlich macht die Route exakt das was sie soll. 
Die Route ist dazu gedacht alle Tasks zurück zu geben, die mit der gegebenen Identity erstellt wurden. 

Der hier beschriebene UseCase - also alle Tasks abfragen, auf die der anfragebende User Zugriff hat - ist etwas anderes. 

Dafür könntest du einmal `getAllSuspendedTasks` ausprobieren. Die gibt dir alle suspendeten ManualTasks, UserTasks und EmptyActivities zurück, auf die du Zugriff hast.

**Comment by ElRaptorus** [comment]
@roblen45  Konntest du das Problem mit `getAllSuspendedTasks` lösen?
