### ISSUE TITLE
🐛 Token Current Is Not Working Correctly

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/process_engine_runtime#534]
## Description

In some cases `token.current` is empty even though it should contain data.

It is easiest to reproduce if two UserTasks are used, one of which accesses the token of the other.

## Reproduction

- Run [this](https://github.com/process-engine/process_engine_runtime/files/4317344/Bier-brauen.bpmn.zip) diagram: 
![Bier-brauen](https://user-images.githubusercontent.com/20394992/76403246-ebbbae80-6384-11ea-8093-406e0a53cd14.png)

- Finish the first task
- Try to finish the second task
- **Notice that the execution of the second task will fail, because `token.current` is empty.**

## My setup

v9.4.1 & v9.5.0

**Comment by ElRaptorus** [comment]
Das Problem liegt wahrscheinlich an der Art und Weise, wie die Management API die Token History aufbaut. Vermutlich werden die Tokens in falscher Reihenfolge in die Fassade geschrieben, wodurch `token.current` nicht den Wert erhält, den es eigentlich sollte. 

https://github.com/process-engine/management_api_core/blob/develop/src/user_task_service.ts#L447 

Den UserTaskService der Consumer API wird das auch betreffen.
