### ISSUE TITLE
⚡️ Correlation is not directly active after running a process

### ISSUE THREAD

**Issue by SteffenKn** [process-engine/process_engine_runtime#54]
#### Describe your issue

This leads to the following bug: https://github.com/process-engine/bpmn-studio/issues/932

#### How can others reproduce the issue?

- Open up the BPMN-Studio
- Run a process with an user task (maybe you need to do this multiple times)
- Notice that the process may stop immediately

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
This is more of a performance issue than a bug. 
There is always a little delay between the time that the command to start a process model is given and the time that the corresponding process instance is actually started (as in the first FlowNode was reached and persisted).

Unfortunately, this is something we have very little control over. We already use sequelize to keep this delay to a minimum, but it's impossible to eliminate it entirely.

Perhaps we could provide a solution with the Socket.io solution that @5ebastianMeier is working on right now. 
We could implement a `process started` notification that the BPMN Studio could wait for. That might at least eliminate this timing issue.

@5ebastianMeier What's your take on this?

**Comment by ElRaptorus** [comment]
@SteffenKn Is this still causing trouble?

**Comment by SteffenKn** [comment]
@ElRaptorus Can't say for sure, but I think it is still causing trouble.
I'll check this.

**Comment by ElRaptorus** [comment]
Prerequisite for this: #134

**Comment by ElRaptorus** [comment]
Since the corresponding BPMN issue was closed and nobody has mentioned this again in the last months, I assume that this is no longer an issue.

If you're still having trouble with this, I strongly recommend you make use of the ConsumerAPIs notification feature.
