### ISSUE TITLE
🐛 UserTasks without process

### ISSUE THREAD

**Issue by Paulomart** [process-engine/process_engine_runtime#548]
Please see the gist for details: https://gist.github.com/Paulomart/c9032e7c6619f6e9e50188c26842702e

**Comment by ElRaptorus** [comment]
Dabei ist zu berücksichtigen, dass das Ganze mit einer Fehlbenutzung der Engine zusammenhängt:

https://gist.github.com/Paulomart/c9032e7c6619f6e9e50188c26842702e#file-test-ts-L44

Der "startProcessInstance" Call muss awaited werden. Das wird hier nicht getan. 

Dadurch entsteht der Effekt, dass das "Terminate Process Instance" Signal gesendet wird, bevor überhaupt ein Task erstmalig seinen State persistiert hat.
D.h. der State der Prozessinstanz ist auf "terminated" gesetzt, die die ProcessEngine führt den Prozess aber trotzdem weiter aus.

**Comment by Paulomart** [comment]
Der Call wird awaited, bevor der Prozess gestoppt wird: https://gist.github.com/Paulomart/c9032e7c6619f6e9e50188c26842702e#file-test-ts-L56

Oder habe ich das falsch verstanden?

**Comment by ElRaptorus** [comment]
Guck mal auf die Zeile die ich verlinkt habe. Da fehlt ein "await".

**Comment by Paulomart** [comment]
Ja das ist auch richtig so, schau bitte einmal auf die Zeile weiter unten, da wird der start Call awaited, bevor der Prozess terminited wird.

**Comment by Paulomart** [comment]
Gibts hier schon was neues?

**Comment by ElRaptorus** [comment]
> Gibts hier schon was neues?

Nur, dass das für die PE nicht umgesetzt wird, weil das ein ziemlich großes Refactoring mit sich zieht. 

Ich würde dich auch bitten künftig Issues [hier](https://github.com/atlas-engine/AtlasEngine.FullstackServer/issues) zu erfassen.

**Comment by Paulomart** [comment]
> Nur, dass das für die PE nicht umgesetzt wird, weil das ein ziemlich großes Refactoring mit sich zieht.
Wir werden das in der Altas Engine fixen.

Okay.

> Ich würde dich auch bitten künftig Issues hier zu erfassen.

Auch Issues welche die PE betreffen?

**Comment by ElRaptorus** [comment]
> Auch Issues welche die PE betreffen? 

Grundsätzlich ja. Die AE baut ja weitestgehend auf dem gleichen Core auf. 

Wenn du aber mit Sicherheit sagen kannst, dass das ein Issue ist, was nur in der PE auftritt, dann kannst du das Issue auch hier aufmachen.
