### ISSUE TITLE
🐛 `.DS_Store` files in `config` folder cause startup to fail.

### ISSUE THREAD

**Issue by Paulomart** [process-engine/process_engine_runtime#558]
`.DS_Store` files in `config` folder cause startup to fail.

This might be also an issue on windows.

**Comment by ElRaptorus** [comment]
Das ist ein Problem mit [nconfetti](https://github.com/5minds/nconfetti), dem Config Provider den wir benutzen. Das muss dort gefixt werden.

**Comment by ElRaptorus** [comment]
FYI: 
In der Atlas Engine haben wir nconfetti als Config Provider gegen nconf getauscht. 
Dort wird dieser Fehler nicht mehr auftreten. 

Da das Ganze ein Refactoring der Config mit sich gezogen hat, werden wir das für die PE nicht mehr nachziehen.
