### ISSUE TITLE
✨ Async notifications through the Consumer API

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/process_engine_runtime#71]
#### Describe your issue

We need to be able to provide notifications to the end user, which contain information about events that were reached.

These notifications can include infos about a process-start, a process-end, the reaching of a user task, events that get executed, etc.

#### Possible Solution

We can implement a new type of extension, based on `socket.io`.

This extension can then provide an endpoint, where clients can subscribe to. The backend can then provide notifications through the appropriate socket.io channel.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
https://github.com/essential-projects/bootstrapper_contracts/pull/2
https://github.com/essential-projects/http_contracts/pull/8
https://github.com/essential-projects/http_node/pull/8
https://github.com/essential-projects/http_extension/pull/9
https://github.com/essential-projects/bootstrapper_node/pull/9

https://github.com/process-engine/process_engine_contracts/pull/68
https://github.com/process-engine/process_engine_core/pull/174

https://github.com/process-engine/consumer_api_contracts/pull/37
https://github.com/process-engine/consumer_api_meta/pull/48
https://github.com/process-engine/consumer_api_client/pull/18
https://github.com/process-engine/consumer_api_core/pull/63
https://github.com/process-engine/consumer_api_http/pull/14

https://github.com/process-engine/management_api_contracts/pull/20
https://github.com/process-engine/management_api_meta/pull/11
https://github.com/process-engine/management_api_client/pull/15
https://github.com/process-engine/management_api_core/pull/16
https://github.com/process-engine/management_api_http/pull/14

**Comment by ElRaptorus** [comment]
@5ebastianMeier 
Please do me a favour and remove all the `^`-type dependencies from the packages you've modified.
We wanted to do this gradually anyway and this is as good a time as any to do it with these packages.

I've rebased the `http_contracts` develop branch into your feature branch. You can use its package.json as reference for the versions to use:
https://github.com/essential-projects/http_contracts/blob/658778cc2d256107658e06bce0b8dab19a3e9c9f/package.json
