### ISSUE TITLE
🐛Can't finish user task if there is a second with the same id.

### ISSUE THREAD

**Issue by Vyperus** [process-engine/process_engine_runtime#94]
#### Describe your issue

Possibly related to: #126  

If two UserTasks with the same id exist, the PE is not able to finish either of them.

#### How can others reproduce the issue?

- Create two diagrams with a UserTask.
- Give those UserTasks the same id.
- Start both diagrams; Don't execute the UserTasks.
- Navigate to the Inspect view and continue one of this UserTasks; Try to execute them.

#### What's your setup

Runtime Version: 2.6.0

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
@Vyperus Do the diagrams use the same correlation ID?

And what exactly happens when you try this? Is there an error thrown?

**Comment by Vyperus** [comment]
Here is a screenshot showing the Problem:

<img width="988" alt="bildschirmfoto 2018-11-06 um 09 36 12" src="https://user-images.githubusercontent.com/17248802/48052142-7a278b00-e1a7-11e8-97fc-5f5dfc811d4d.png">

The correlation ID is different, but if you try to `Confirm` one those UserTasks the Usertask just reappears with the message `Process continued`.

You can reproduce this by:

1. Import this diagram
[HTTP REST API.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/2552222/HTTP.REST.API.bpmn.zip)

2. Start it once.
3. `Cancel` the appearing UserTask.
4. Start another instance.
5. Try to `Confirm` this task.

**Comment by ElRaptorus** [comment]
@Vyperus Thx, I'll have a look as soon as I can.

**Comment by ElRaptorus** [comment]
@Vyperus I think I may have identified the problem.
This could be related to this:
https://github.com/process-engine/process_engine_core/issues/187

**Comment by ElRaptorus** [comment]
Successfully fixed in #130
